package com.alag.test.business.module.a.api.model;

import java.io.Serializable;

public class AUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_user.u_no
     *
     * @mbggenerated Fri Feb 08 19:47:54 CST 2019
     */
    private Integer uNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_user.u_name
     *
     * @mbggenerated Fri Feb 08 19:47:54 CST 2019
     */
    private String uName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_user.u_balance
     *
     * @mbggenerated Fri Feb 08 19:47:54 CST 2019
     */
    private Long uBalance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_user.u_no
     *
     * @return the value of a_user.u_no
     *
     * @mbggenerated Fri Feb 08 19:47:54 CST 2019
     */
    public Integer getuNo() {
        return uNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_user.u_no
     *
     * @param uNo the value for a_user.u_no
     *
     * @mbggenerated Fri Feb 08 19:47:54 CST 2019
     */
    public void setuNo(Integer uNo) {
        this.uNo = uNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_user.u_name
     *
     * @return the value of a_user.u_name
     *
     * @mbggenerated Fri Feb 08 19:47:54 CST 2019
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_user.u_name
     *
     * @param uName the value for a_user.u_name
     *
     * @mbggenerated Fri Feb 08 19:47:54 CST 2019
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_user.u_balance
     *
     * @return the value of a_user.u_balance
     *
     * @mbggenerated Fri Feb 08 19:47:54 CST 2019
     */
    public Long getuBalance() {
        return uBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_user.u_balance
     *
     * @param uBalance the value for a_user.u_balance
     *
     * @mbggenerated Fri Feb 08 19:47:54 CST 2019
     */
    public void setuBalance(Long uBalance) {
        this.uBalance = uBalance;
    }
}