package com.alag.test.business.module.a.server.mapper;

import com.alag.test.business.module.a.api.model.AUser;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user
     *
     * @mbggenerated Fri Feb 08 19:47:54 CST 2019
     */
    int deleteByPrimaryKey(Integer uNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user
     *
     * @mbggenerated Fri Feb 08 19:47:54 CST 2019
     */
    int insert(AUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user
     *
     * @mbggenerated Fri Feb 08 19:47:54 CST 2019
     */
    int insertSelective(AUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user
     *
     * @mbggenerated Fri Feb 08 19:47:54 CST 2019
     */
    AUser selectByPrimaryKey(Integer uNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user
     *
     * @mbggenerated Fri Feb 08 19:47:54 CST 2019
     */
    int updateByPrimaryKeySelective(AUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user
     *
     * @mbggenerated Fri Feb 08 19:47:54 CST 2019
     */
    int updateByPrimaryKey(AUser record);

    int addMoneyById(@Param("id") int i, @Param("money") long money);

    int minusMoneyById(@Param("id") int i, @Param("money") long money);
}