package com.alag.test.business.module.message.server.mapper;

import com.alag.test.business.core.common.page.PageParam;
import com.alag.test.business.module.message.api.model.TransactionMessage;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface TransactionMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_message
     *
     * @mbggenerated Wed Feb 27 23:29:24 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_message
     *
     * @mbggenerated Wed Feb 27 23:29:24 CST 2019
     */
    int insert(TransactionMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_message
     *
     * @mbggenerated Wed Feb 27 23:29:24 CST 2019
     */
    int insertSelective(TransactionMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_message
     *
     * @mbggenerated Wed Feb 27 23:29:24 CST 2019
     */
    TransactionMessage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_message
     *
     * @mbggenerated Wed Feb 27 23:29:24 CST 2019
     */
    int updateByPrimaryKeySelective(TransactionMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_message
     *
     * @mbggenerated Wed Feb 27 23:29:24 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(TransactionMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_message
     *
     * @mbggenerated Wed Feb 27 23:29:24 CST 2019
     */
    int updateByPrimaryKey(TransactionMessage record);

    TransactionMessage getMsgById(String messageId);

    Long countMessageInDeadByQueueName(PageParam pageParam);

    List<Object> selectDeadMsgByQName(Map<String, Object> paramMap);
}